# frozen_string_literal: true

namespace :products do
  desc "Update product data based on product name"
  task update_data: :environment do
    data_to_update = {
      "armchair"          => {height: 97, width: 77, length: 47, material: "Wood", subcategory_id: 16},
      "armoire"           => {height: 2200, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "bar stool"         => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 16},
      "bassinet"          => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 7},
      "beach chair"       => {height: 12, width: 22, length: 72, material: "Polyester", subcategory_id: 18},
      "bean bag chair"    => {height: 24, width: 36, length: 36, material: "Memory Foam", subcategory_id: 16},
      "bed"               => {height: 400, width: 1260, length: 1960, material: "Wood", subcategory_id: 7},
      "bed table"         => {height: 500, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "bench"             => {height: 50, width: 35, length: 80, material: "Wood", subcategory_id: 17},
      "bentwood rocker"   => {height: 110, width: 60, length: 105, material: "Wood", subcategory_id: 15},
      "bergere"           => {height: 74, width: 50, length: 54, material: "Artificial suede", subcategory_id: 16},
      "bookcase"          => {height: 2200, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "bookshelf"         => {height: 2000, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "breakfront"        => {height: 1200, width: 1000, length: 520, material: "Wood", subcategory_id: 3},
      "buffet"            => {height: 2200, width: 1200, length: 520, material: "Wood", subcategory_id: 3},
      "bunk bed"          => {height: 1060, width: 360, length: 590, material: "Wood", subcategory_id: 7},
      "bureau"            => {height: 1200, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "cabinet"           => {height: 1040, width: 560, length: 690, material: "Wood", subcategory_id: 4},
      "canopy bed"        => {height: 650, width: 430, length: 1080, material: "Wood", subcategory_id: 7},
      "captain's chair"   => {height: 540, width: 60, length: 90, material: "Wood", subcategory_id: 13},
      "card table"        => {height: 100, width: 80, length: 100, material: "Metal", subcategory_id: 11},
      "carpet"            => {height: 20, width: 160, length: 200, material: "Microfiber", subcategory_id: 24},
      "cart"              => {height: 250, width: 100, length: 120, material: "Plastic", subcategory_id: 26},
      "chair"             => {height: 50, width: 60, length: 90, material: "Wood", subcategory_id: 16},
      "chaise lounge"     => {height: 50, width: 100, length: 280, material: "Plastic", subcategory_id: 18},
      "chandelier"        => {height: 40, width: 60, length: 90, material: "Metal", subcategory_id: 19},
      "chest"             => {height: 560, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "chest of drawers"  => {height: 1200, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "china cabinet"     => {height: 2200, width: 1000, length: 520, material: "Wood", subcategory_id: 3},
      "clothes valet"     => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 6},
      "club chair"        => {height: 50, width: 30, length: 80, material: "Faux Leather", subcategory_id: 16},
      "coffee table"      => {height: 40, width: 60, length: 90, material: "Metal", subcategory_id: 12},
      "console"           => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 12},
      "cot"               => {height: 40, width: 60, length: 90, material: "Metal", subcategory_id: 18},
      "couch"             => {height: 150, width: 330, length: 180, material: "Faux Leather", subcategory_id: 1},
      "cradle"            => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 7},
      "credenza"          => {height: 500, width: 1000, length: 520, material: "Wood", subcategory_id: 6},
      "crib"              => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 7},
      "cubbies"           => {height: 2200, width: 1000, length: 520, material: "Wood", subcategory_id: 6},
      "cupboard"          => {height: 2200, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "curio"             => {height: 2200, width: 1000, length: 520, material: "Wood", subcategory_id: 6},
      "curtains"          => {height: 240, width: 160, length: 10, material: "Polyester", subcategory_id: 20},
      "cushion"           => {height: 20, width: 30, length: 30, material: "Polyester", subcategory_id: 21},
      "deck chair"        => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 9},
      "desk"              => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 12},
      "desk chair"        => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 18},
      "dining room table" => {height: 50, width: 130, length: 280, material: "Wood", subcategory_id: 9},
      "director's chair"  => {height: 40, width: 160, length: 290, material: "Faux Leather", subcategory_id: 13},
      "display cabinet"   => {height: 2200, width: 1000, length: 520, material: "Wood", subcategory_id: 3},
      "divan"             => {height: 40, width: 160, length: 190, material: "Faux Leather", subcategory_id: 1},
      "drapery"           => {height: 50, width: 30, length: 80, material: "Polyester", subcategory_id: 20},
      "drapes"            => {height: 40, width: 60, length: 90, material: "Polyester", subcategory_id: 20},
      "dresser"           => {height: 620, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "easel"             => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 26},
      "easy chair"        => {height: 50, width: 30, length: 80, material: "Polyester", subcategory_id: 16},
      "end table"         => {height: 550, width: 1000, length: 520, material: "Wood", subcategory_id: 6},
      "fauteuil"          => {height: 50, width: 30, length: 80, material: "Faux Leather", subcategory_id: 16},
      "file cabinet"      => {height: 40, width: 60, length: 90, material: "Metal", subcategory_id: 5},
      "folding chair"     => {height: 50, width: 30, length: 80, material: "Metal", subcategory_id: 16},
      "folding screen"    => {height: 440, width: 160, length: 190, material: "Bamboo", subcategory_id: 25},
      "footrest"          => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 2},
      "footstool"         => {height: 40, width: 60, length: 90, material: "Polyester", subcategory_id: 2},
      "four-poster bed"   => {height: 50, width: 330, length: 380, material: "Wood", subcategory_id: 7},
      "furnishings"       => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 26},
      "furniture"         => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 1},
      "futon"             => {height: 40, width: 360, length: 590, material: "Foam", subcategory_id: 8},
      "game table"        => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 11},
      "garden bench"      => {height: 40, width: 60, length: 190, material: "Metal", subcategory_id: 17},
      "gateleg table"     => {height: 100, width: 30, length: 80, material: "Metal", subcategory_id: 12},
      "glider rocker"     => {height: 40, width: 260, length: 290, material: "Wood", subcategory_id: 15},
      "grandfather clock" => {height: 450, width: 30, length: 80, material: "Wood", subcategory_id: 23},
      "hall tree"         => {height: 2200, width: 1000, length: 520, material: "Wood", subcategory_id: 6},
      "hammock"           => {height: 50, width: 30, length: 280, material: "Cotton", subcategory_id: 18},
      "hassock"           => {height: 40, width: 60, length: 90, material: "Polyester", subcategory_id: 2},
      "hat stand"         => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 6},
      "headboard"         => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 7},
      "highchair"         => {height: 50, width: 30, length: 80, material: "Plastic", subcategory_id: 16},
      "hope chest"        => {height: 520, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "hutch"             => {height: 2000, width: 1000, length: 520, material: "Wood", subcategory_id: 3},
      "island"            => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 12},
      "kitchen island"    => {height: 50, width: 130, length: 190, material: "Wood", subcategory_id: 12},
      "ladderback chair"  => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 14},
      "lamp"              => {height: 50, width: 30, length: 80, material: "Linen", subcategory_id: 19},
      "lawn chair"        => {height: 40, width: 60, length: 90, material: "Cotton", subcategory_id: 18},
      "lift chair"        => {height: 50, width: 70, length: 80, material: "Wood", subcategory_id: 16},
      "light"             => {height: 40, width: 60, length: 90, material: "Plastic", subcategory_id: 19},
      "lintel"            => {height: 50, width: 30, length: 80, material: "Plastic", subcategory_id: 19},
      "lounge chair"      => {height: 40, width: 60, length: 90, material: "Bamboo", subcategory_id: 16},
      "lounger"           => {height: 50, width: 30, length: 80, material: "Plastic", subcategory_id: 18},
      "love seat"         => {height: 40, width: 60, length: 90, material: "Cotton", subcategory_id: 1},
      "mantle"            => {height: 50, width: 30, length: 80, material: "Cotton", subcategory_id: 21},
      "mattress"          => {height: 40, width: 560, length: 490, material: "Foam", subcategory_id: 8},
      "mirror"            => {height: 50, width: 30, length: 80, material: "Metal", subcategory_id: 22},
      "Murphy bed"        => {height: 60, width: 660, length: 690, material: "Wood", subcategory_id: 7},
      "nightstand"        => {height: 520, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "office chair"      => {height: 40, width: 60, length: 90, material: "Plastic", subcategory_id: 13},
      "ottoman"           => {height: 50, width: 30, length: 80, material: "Cotton", subcategory_id: 2},
      "pantry"            => {height: 2000, width: 1000, length: 520, material: "Wood", subcategory_id: 6},
      "park bench"        => {height: 50, width: 90, length: 180, material: "Wood", subcategory_id: 17},
      "patio chair"       => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 16},
      "patio table"       => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 10},
      "pew"               => {height: 40, width: 60, length: 90, material: "Metal", subcategory_id: 17},
      "piano bench"       => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 16},
      "picnic table"      => {height: 40, width: 60, length: 90, material: "Metal", subcategory_id: 10},
      "pillow"            => {height: 50, width: 30, length: 80, material: "Foam", subcategory_id: 21},
      "porch swing"       => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 15},
      "rack"              => {height: 2200, width: 1000, length: 520, material: "Metal", subcategory_id: 5},
      "recliner"          => {height: 40, width: 60, length: 90, material: "Plastic", subcategory_id: 16},
      "rocking chair"     => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 15},
      "room divider"      => {height: 40, width: 60, length: 90, material: "Bamboo", subcategory_id: 25},
      "rug"               => {height: 50, width: 180, length: 180, material: "Cotton", subcategory_id: 24},
      "sconce"            => {height: 40, width: 60, length: 90, material: "Metal", subcategory_id: 19},
      "screen"            => {height: 450, width: 300, length: 480, material: "Bamboo", subcategory_id: 25},
      "seat"              => {height: 40, width: 60, length: 90, material: "Cotton", subcategory_id: 16},
      "secretary"         => {height: 50, width: 30, length: 80, material: "Metal", subcategory_id: 13},
      "sectional sofa"    => {height: 40, width: 60, length: 190, material: "Wood", subcategory_id: 1},
      "settee"            => {height: 50, width: 30, length: 180, material: "Polyester", subcategory_id: 1},
      "shelf"             => {height: 1500, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "shoji screen"      => {height: 1800, width: 1000, length: 520, material: "Wood", subcategory_id: 25},
      "sideboard"         => {height: 2200, width: 1000, length: 520, material: "Wood", subcategory_id: 3},
      "sleeper sofa"      => {height: 50, width: 30, length: 180, material: "Cotton", subcategory_id: 1},
      "sofa"              => {height: 40, width: 60, length: 190, material: "Cotton", subcategory_id: 1},
      "sofabed"           => {height: 50, width: 30, length: 80, material: "Cotton", subcategory_id: 1},
      "stool"             => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 14},
      "table"             => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 12},
      "tansu"             => {height: 500, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "tea cart"          => {height: 450, width: 330, length: 480, material: "Metal", subcategory_id: 26},
      "throne"            => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 16},
      "throw rug"         => {height: 50, width: 30, length: 80, material: "Cotton", subcategory_id: 24},
      "trundle bed"       => {height: 40, width: 260, length: 390, material: "Metal", subcategory_id: 7},
      "tuffet"            => {height: 50, width: 30, length: 80, material: "Polyester", subcategory_id: 2},
      "valet"             => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 6},
      "vanity"            => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 9},
      "Venetian blinds"   => {height: 40, width: 60, length: 90, material: "Vinyl", subcategory_id: 20},
      "vitrine"           => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 3},
      "wardrobe"          => {height: 2200, width: 1000, length: 520, material: "Wood", subcategory_id: 4},
      "waste basket"      => {height: 50, width: 30, length: 80, material: "Plastic", subcategory_id: 26},
      "waterbed"          => {height: 40, width: 360, length: 590, material: "Wood", subcategory_id: 7},
      "window shades"     => {height: 50, width: 30, length: 80, material: "Cotton", subcategory_id: 20},
      "Windsor chair"     => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 14},
      "wing chair"        => {height: 50, width: 30, length: 80, material: "Cotton", subcategory_id: 16},
      "work table"        => {height: 40, width: 60, length: 90, material: "Wood", subcategory_id: 13},
      "writing desk"      => {height: 50, width: 30, length: 80, material: "Wood", subcategory_id: 9}
    }

    data_to_update.each do |product_name, product_data|
      product = Product.find_by(name: product_name)

      if product.present?
        random_price = rand(500..10_000)
        random_color = if product.name.downcase == "mattress"
                         "white"
                       else
                         %w[white black brown red grey].sample
                       end
        product.update(product_data.merge(
                         price:        random_price,
                         color:        random_color,
                         producer_id:  1,
                         availability: "true"
                       ))
      else
        puts "Product '#{product_name}' not found!"
      end
    end

    puts "Product data updated successfully!"
  end
end
