default: &default
  adapter: postgresql
  encoding: unicode
  database: furniture_online_store_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: furniture_online_store_development
  username: postgres
  password: postgres
  host: localhost
  port: 5432

test:
  <<: *default
  database: furniture_online_store_test

production:
  <<: *default
  database: furniture_online_store_production
  username: furniture_online_store
  password: <%= ENV["FURNITURE_ONLINE_STORE_DATABASE_PASSWORD"] %>
